services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 carportal.wsgi:application
    volumes:
      - .:/app
      - ./static:/app/static # Монтируем весь проект Чтобы SQLite сохранялась между перезапусками
    ports:
      - "8000:8000"                # Пробрасываем порт 8000
    environment:
      - DEBUG=1                    # Режим отладки (для разработки)

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  # Монтируем папку static напрямую
    depends_on:
      - web